import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import './styles.css';

const genres = [{ id: '', label: 'All films' }, { id: '28', label: 'Action' }, { id: '12', label: 'Adventure' }, { id: '35', label: 'Comedy' }, { id: '18', label: 'Drama' }, { id: '27', label: 'Horror' }, { id: '878', label: 'Sci-Fi' }, { id: '53', label: 'Thriller' }];
const fmtDate = date => date ? new Date(date).getFullYear() : '—';
const fallbackPoster = 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=85';

function useWishlist() {
  const [wishlist, setWishlist] = useState([]);
  useEffect(() => { fetch('/api/wishlist').then(r => r.json()).then(d => setWishlist(d.movies || [])).catch(() => {}); }, []);
  const ids = useMemo(() => new Set(wishlist.map(m => m.id || m.movie_id)), [wishlist]);
  async function toggle(movie) {
    if (ids.has(movie.id)) { await fetch(`/api/wishlist/${movie.id}`, { method: 'DELETE' }); setWishlist(items => items.filter(item => (item.id || item.movie_id) !== movie.id)); }
    else { const response = await fetch('/api/wishlist', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(movie) }); const data = await response.json(); if (data.movie) setWishlist(items => [data.movie, ...items]); }
  }
  return { wishlist, ids, toggle };
}

function App() { const wishlistState = useWishlist(); return <><Header count={wishlistState.wishlist.length} /><Routes><Route path="/" element={<Home wishlistState={wishlistState} />} /><Route path="/search" element={<Home wishlistState={wishlistState} />} /><Route path="/movie/:id" element={<Details wishlistState={wishlistState} />} /><Route path="/wishlist" element={<Wishlist wishlistState={wishlistState} />} /></Routes><Footer /></>; }

function Header({ count }) { const [open, setOpen] = useState(false); const navigate = useNavigate(); const [query, setQuery] = useState('');
  function submit(e) { e.preventDefault(); if (query.trim()) navigate(`/search?query=${encodeURIComponent(query.trim())}`); }
  return <header className="topbar"><div className="nav-wrap"><Link to="/" className="brand"><span className="brand-mark">✦</span><span>Screen<span className="muted-brand">Atlas</span></span></Link><form onSubmit={submit} className={`search ${open ? 'search-open' : ''}`}><span className="search-icon">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} onFocus={() => setOpen(true)} placeholder="Search titles, people, genres..." aria-label="Search movies"/><button type="button" className="search-close" onClick={() => { setQuery(''); setOpen(false); }}>×</button></form><nav><Link className="nav-link" to="/">Discover</Link><Link className="nav-link wishlist-link" to="/wishlist"><span>♥</span> Wishlist {count > 0 && <b>{count}</b>}</Link></nav></div></header>;
}

function Home({ wishlistState }) { const location = useLocation(); const params = new URLSearchParams(location.search); const query = params.get('query') || ''; const [sort, setSort] = useState('popular'); const [genre, setGenre] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState({ movies: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { setPage(1); }, [query, genre, sort]);
  useEffect(() => { let active = true; setLoading(true); setError(''); const endpoint = query ? `/api/search?query=${encodeURIComponent(query)}&page=${page}` : `/api/discover?page=${page}&sort=${sort}&genre=${genre}`; fetch(endpoint).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to load films'); return d; }).then(d => active && setData(prev => page === 1 ? d : { ...d, movies: [...prev.movies, ...d.movies] })).catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [query, genre, sort, page]);
  const title = query ? `Results for “${query}”` : 'Find your next favourite';
  return <main><section className="hero"><div className="hero-inner"><div className="eyebrow">THE CURATED SCREEN</div><h1>{title}</h1><p>{query ? 'A hand-picked trail through the movies that match your search.' : 'A little inspiration for your next great watch.'}</p><div className="hero-actions"><Link to="/search?query=award winning" className="pill-button">Explore a theme <span>→</span></Link><Link to="/wishlist" className="text-button">Your watchlist <span>→</span></Link></div></div><div className="hero-orbit orbit-one"></div><div className="hero-orbit orbit-two"></div><div className="hero-star">✦</div></section><section className="content"><div className="section-heading"><div><span className="eyebrow">BROWSE THE COLLECTION</span><h2>{query ? 'Matching titles' : 'Made for movie people'}</h2></div><div className="sorter"><label htmlFor="sort">Sort by</label><select id="sort" value={sort} onChange={e => setSort(e.target.value)} disabled={Boolean(query)}><option value="popular">Most popular</option><option value="rating">Top rated</option><option value="newest">Newest first</option></select></div></div><div className="chips">{genres.map(item => <button key={item.id} className={`chip ${genre === item.id ? 'active' : ''}`} onClick={() => setGenre(item.id)}>{item.label}</button>)}</div>{data.warning && <div className="notice">{data.warning}</div>}{error && <div className="error-state"><span>!</span><div><strong>We hit a snag.</strong><p>{error}</p><button onClick={() => setPage(page)}>Try again</button></div></div>}{loading && page === 1 ? <Skeletons /> : !loading && data.movies.length === 0 ? <Empty query={query} /> : <><div className="movie-grid">{data.movies.map(movie => <MovieCard movie={movie} key={movie.id} saved={wishlistState.ids.has(movie.id)} onToggle={wishlistState.toggle} />)}</div>{data.page < data.totalPages && <button className="load-more" onClick={() => setPage(current => current + 1)} disabled={loading}>{loading ? 'Loading...' : 'Load more films'} <span>↓</span></button>}</>}</section></main>;
}

function MovieCard({ movie, saved, onToggle }) { const location = useLocation(); const detailState = { from: `${location.pathname}${location.search}` }; return <article className="movie-card"><Link to={`/movie/${movie.id}`} state={detailState} className="poster-wrap"><img src={movie.posterUrl || fallbackPoster} alt={`${movie.title} poster`} loading="lazy"/><span className="poster-fade"></span><button className={`save-button ${saved ? 'saved' : ''}`} aria-label={saved ? 'Remove from wishlist' : 'Add to wishlist'} onClick={e => { e.preventDefault(); e.stopPropagation(); onToggle(movie); }}>{saved ? '♥' : '♡'}</button><span className="rating-badge">★ {movie.rating ? movie.rating.toFixed(1) : '—'}</span></Link><div className="movie-card-copy"><Link to={`/movie/${movie.id}`} state={detailState}><h3>{movie.title}</h3></Link><p>{fmtDate(movie.releaseDate)} <span>•</span> {(movie.genres || []).slice(0, 2).join(' / ') || 'Feature film'}</p></div></article>; }
function Skeletons() { return <div className="movie-grid">{Array.from({ length: 8 }).map((_, i) => <div className="skeleton-card" key={i}><div className="skeleton poster-skeleton"></div><div className="skeleton line-skeleton"></div><div className="skeleton short-skeleton"></div></div>)}</div>; }
function Empty({ query }) { return <div className="empty-state"><div className="empty-icon">⌕</div><h3>No films found{query ? ` for “${query}”` : ''}</h3><p>Try a broader search or explore one of the collections above.</p></div>; }

function Details({ wishlistState }) { const { id } = useParams(); const location = useLocation(); const [movie, setMovie] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { fetch(`/api/movies/${id}`).then(r => r.json()).then(d => { if (d.error) throw new Error(d.error); setMovie(d); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]); if (loading) return <main className="detail-loading"><div className="spinner"></div></main>; if (error || !movie) return <main className="detail-loading"><Empty query="this film" /></main>; const saved = wishlistState.ids.has(movie.id); const backTarget = location.state?.from || '/'; return <main className="details"><div className="detail-backdrop" style={{ backgroundImage: `linear-gradient(90deg, #0b0d12 0%, rgba(11,13,18,.8) 42%, rgba(11,13,18,.18) 100%), linear-gradient(0deg, #0b0d12 1%, transparent 70%), url(${movie.backdropUrl || movie.posterUrl || fallbackPoster})` }}></div><div className="detail-content"><Link to={backTarget} className="back-link">← Back to discovery</Link><div className="detail-copy"><div className="eyebrow">FEATURED TITLE</div><h1>{movie.title}</h1>{movie.tagline && <p className="tagline">{movie.tagline}</p>}<div className="detail-meta"><span className="score">★ {movie.rating?.toFixed(1)}</span><span>{fmtDate(movie.releaseDate)}</span>{movie.runtime && <span>{movie.runtime} min</span>}<span>{movie.genres?.join(' · ')}</span></div><p className="overview">{movie.overview}</p><div className="detail-actions"><button className={`primary-action ${saved ? 'is-saved' : ''}`} onClick={() => wishlistState.toggle(movie)}>{saved ? '♥ Saved to wishlist' : '♡ Add to wishlist'}</button>{movie.trailerKey && <a className="secondary-action" href={`https://www.youtube.com/watch?v=${movie.trailerKey}`} target="_blank" rel="noreferrer">Watch trailer ↗</a>}</div>{movie.cast?.length > 0 && <div className="cast"><span className="eyebrow">CAST</span><div className="cast-row">{movie.cast.slice(0, 5).map(person => <div className="cast-person" key={person.id}><img src={person.photoUrl || fallbackPoster} alt=""/><span>{person.name}</span><small>{person.character}</small></div>)}</div></div>}</div></div></main>; }

function Wishlist({ wishlistState }) { return <main className="content wishlist-page"><div className="wishlist-heading"><div><span className="eyebrow">YOUR PERSONAL SHELF</span><h1>Wishlist</h1><p>{wishlistState.wishlist.length ? `${wishlistState.wishlist.length} title${wishlistState.wishlist.length === 1 ? '' : 's'} saved for later.` : 'Keep a running list of films you want to remember.'}</p></div><span className="wishlist-count">{String(wishlistState.wishlist.length).padStart(2, '0')}</span></div>{wishlistState.wishlist.length ? <div className="movie-grid">{wishlistState.wishlist.map(movie => <MovieCard movie={{ ...movie, id: movie.id || movie.movie_id, posterUrl: movie.posterUrl || movie.poster_path, releaseDate: movie.releaseDate || movie.release_date, rating: movie.rating || movie.vote_average }} saved onToggle={wishlistState.toggle} key={movie.id || movie.movie_id} />)}</div> : <div className="empty-state wishlist-empty"><div className="empty-icon">♥</div><h3>Your shelf is waiting</h3><p>Save a film while browsing and it will be here when you return.</p><Link to="/" className="pill-button">Start discovering <span>→</span></Link></div>}</main>; }
function Footer() { return <footer><span>SCREENATLAS</span><span>For curious viewers · Built for the next great watch</span></footer>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
